version: '2'

services:
  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    container_name: "php"
    volumes:
      - ./src:/src

  mysql:
    image: mysql
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
